- name: Nextcloud Installation and Configuration
  hosts: nextcloud
  become: yes
  vars:
    db_name: "dbnextcloud"     
    db_user: "dbuser"       
    db_password: "dbpassword"  
    nextcloud_admin_user: "admin" 
    nextcloud_admin_password: "admin" 
  tasks:
    - name: Set Timezone to Europe/Moscow
      community.general.timezone:
        name: Europe/Moscow

    - name: Update package cache and upgrade system
      ansible.builtin.apt:
        update_cache: true
        upgrade: "yes"

    - name: Install required dependencies
      ansible.builtin.apt:
        pkg:
          - apache2
          - libapache2-mod-php
          - acl
          - php-curl
          - php-gd
          - php-json
          - php-mbstring
          - php-xml
          - php-zip
          - php-intl
          - php-mysql
          - php-pgsql
          - php-bcmath
          - unzip
          - python3-pip
          - postgresql
          - postgresql-contrib
          - postgresql-all
          - wget
          - bzip2
        state: present

    - name: Install psycopg2 Python library
      ansible.builtin.pip:
        extra_args: "--break-system-packages"
        name: psycopg2

    - name: Download and unpack Nextcloud
      ansible.builtin.unarchive:
        dest: "/var/www/html"
        src: "https://download.nextcloud.com/server/releases/latest-30.tar.bz2"
        remote_src: true
        owner: "www-data"
        group: "www-data"
        creates: "/var/www/html/nextcloud"

    - name: Start and enable Apache and PostgreSQL services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - postgresql

    - name: Create PostgreSQL user for Nextcloud
      become: true
      become_user: postgres
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        db: "{{ db_name }}"
        role_attr_flags: "CREATEDB,LOGIN"
        state: present

    - name: Create PostgreSQL database for Nextcloud
      become: true
      become_user: postgres
      postgresql_db:
        name: "{{ db_name }}"
        encoding: "UTF8"
        lc_ctype: "en_US.UTF-8"
        lc_collate: "en_US.UTF-8"
        state: present

    - name: Check if PostgreSQL database is initialized
      stat:
        path: /var/lib/pgsql/14/data/pg_hba.conf
      register: result

    - name: Configure Apache for Nextcloud
      copy:
        dest: "/etc/apache2/sites-available/nextcloud.conf"
        content: |
          <VirtualHost *:80>
              DocumentRoot "/var/www/html/nextcloud"
              ServerName vvot3.itiscl.ru
              ServerAlias 176.52.100.227
              ServerAlias 2001:db8::1234  # Add IPv6 address
              <Directory "/var/www/html/nextcloud">
                  Options FollowSymlinks
                  AllowOverride All
                  Require all granted
              </Directory>
              ErrorLog ${APACHE_LOG_DIR}/vvot3_error.log
              CustomLog ${APACHE_LOG_DIR}/vvot3_access.log combined
          </VirtualHost>
      notify: Restart Apache

    - name: Enable Nextcloud site in Apache
      file:
        src: "/etc/apache2/sites-available/nextcloud.conf"
        dest: "/etc/apache2/sites-enabled/nextcloud.conf"
        state: link

    - name: Check if Nextcloud configuration exists
      stat:
        path: /var/www/html/nextcloud/config/config.php
      register: nextcloud_config

    - name: Configure Nextcloud using occ command
      shell: |
        cd /var/www/html/nextcloud
        sudo -u www-data php occ maintenance:install \
          --database "pgsql" \
          --database-name "{{ db_name }}" \
          --database-user "{{ db_user }}" \
          --database-pass "{{ db_password }}" \
          --admin-user "{{ nextcloud_admin_user }}" \
          --admin-pass "{{ nextcloud_admin_password }}"
      when: not nextcloud_config.stat.exists

    - name: Add trusted domains to Nextcloud configuration
      lineinfile:
        path: /var/www/html/nextcloud/config/config.php
        regexp: "^\\s*'trusted_domains' =>"
        line: |
          'trusted_domains' => array (
              0 => 'localhost',
              1 => '176.52.100.227',
              2 => 'vvot3.itiscl.ru',
              3 => '2001:db8::1234',  # Add IPv6 address
          ),
        insertafter: "'instanceid' =>"

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted